name: Cypress Tests

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports: 
          - 27017:27017

      steep:
        image: steep/steep:unstable
        ports: 
          - 8081:8081
        env: 
          STEEP_HTTP_HOST: 0.0.0.0
          STEEP_HTTP_PORT: 8081
          STEEP_DB_DRIVER: mongodb
          STEEP_DB_URL: mongodb://mongo:27017/steep

    steps:
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 12

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add data to VMS collection
        run: mongoimport --collection=vms --db=steep --file=${{ github.workspace }}/ui/cypress/fixtures/steep_vms.json

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./ui
          browser: chrome
          wait-on: http://localhost:8081
          wait-on-timeout: 300
          config: baseUrl=http://localhost:8081

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ui/cypress/screenshots
